background            #000000
foreground            #f3e1b9

# black
color0  #000000
color8  #6B5B95

# red
color1  #b02922
color9  #d94a42

# green
color2  #31b192
color10 #5DD4B8

# yellow
color3  #f1a11d
color11 #F5C04A

# blue
color4  #0987d0
color12 #5bb8e8

# magenta
color5  #c172d4
color13 #d994e0

#cyan
color6  #59d8e6
color14 #8ce6f0

#white
color7  #f3e1b9
color15 #ffffff


